version: '3.8'

services:
  # El contenedor de tu ERP de Django
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DB_HOST=db
      - DB_NAME=costos_db
      - DB_USER=juan_camilo
      - DB_PASSWORD=costos_secret_pass
    depends_on:
      - db

  # El contenedor de la Base de Datos PostgreSQL
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=costos_db
      - POSTGRES_USER=juan_camilo
      - POSTGRES_PASSWORD=costos_secret_pass
    ports:
      - "5432:5432"

volumes:
  postgres_data: