# Generated by Django 4.2.11 on 2026-05-17 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('codigo_iso', models.CharField(max_length=3, unique=True)),
                ('tasa_patronal_estandar', models.DecimalField(decimal_places=4, max_digits=5)),
                ('tasa_patronal_temporal', models.DecimalField(decimal_places=4, max_digits=5)),
                ('salario_minimo', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Países',
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proyecto', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('kwh_estimados_mes', models.DecimalField(decimal_places=2, help_text='Consumo proyectado de energía al mes en kWh', max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cargo', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo_contable', models.CharField(choices=[('COSTO', 'Costo (Mano de Obra Directa / Operación)'), ('GASTO', 'Gasto (Administrativo / Ventas)')], default='COSTO', max_length=5)),
            ],
            options={
                'verbose_name_plural': 'Roles / Cargos',
            },
        ),
        migrations.CreateModel(
            name='RegistroEnergia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField()),
                ('año', models.IntegerField()),
                ('total_kwh_consumidos_real', models.DecimalField(decimal_places=2, max_digits=12)),
                ('costo_total_recibo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos_energia', to='costos_app.pais')),
            ],
            options={
                'verbose_name': 'Registro de Energía',
                'verbose_name_plural': 'Registros de Energía',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('salario_bruto_mensual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_contrato', models.CharField(choices=[('INDEFINIDO', 'Término Indefinido'), ('FIJO', 'Término Fijo / Obra')], default='INDEFINIDO', max_length=10)),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empleados', to='costos_app.pais')),
                ('rol', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleados', to='costos_app.rol')),
            ],
        ),
    ]
