# Generated by Django 4.2.11 on 2026-05-18 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costos_app', '0002_alter_empleado_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleado',
            options={},
        ),
    ]
