# Generated by Django 4.2.11 on 2026-05-18 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costos_app', '0004_alter_empleado_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pais',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='registroenergia',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='rol',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='PoliticaContratacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_contrato', models.CharField(choices=[('INDEFINIDO', 'Término Indefinido'), ('FIJO', 'Término Fijo / Obra')], help_text='El tipo de contrato al que se le aplicará esta norma legal', max_length=10)),
                ('duracion_maxima_meses', models.IntegerField(blank=True, help_text='Duración máxima permitida por ley (Ej: 24 meses para FIJO en Lituania). Dejar vacío si no aplica.', null=True)),
                ('periodo_prueba_maximo_meses', models.IntegerField(default=3, help_text='Meses máximos de prueba permitidos por la legislación local.')),
                ('porcentaje_maximo_nomina', models.DecimalField(blank=True, decimal_places=2, help_text='Límite de empleados con este contrato (Ej: Max 20.00% de la nómina para contratos fijos).', max_digits=5, null=True)),
                ('observacion_legal', models.TextField(blank=True, help_text='Notas o textos legales adicionales sobre las condiciones de despido o preaviso.', null=True)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='politicas_contratacion', to='costos_app.pais')),
            ],
            options={
                'verbose_name': 'Política de Contratación',
                'verbose_name_plural': 'Políticas de Contratación',
                'unique_together': {('pais', 'tipo_contrato')},
            },
        ),
    ]
