# Generated by Django 4.2.11 on 2026-05-19 04:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('costos_app', '0005_alter_empleado_id_alter_pais_id_alter_proyecto_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='kwh_estimados_mes',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='nombre_proyecto',
        ),
        migrations.AddField(
            model_name='empleado',
            name='costo_seguridad_social_mes',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='empleado',
            name='provision_prestaciones_mes',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='fecha_inicio',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proyecto',
            name='nombre',
            field=models.CharField(default='Proyecto Temporal', max_length=150),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='AsignacionProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas_dedicadas', models.FloatField()),
                ('mes_ano', models.CharField(max_length=7)),
                ('costo_imputado_al_proyecto', models.FloatField(default=0.0)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='costos_app.empleado')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='costos_app.proyecto')),
            ],
        ),
    ]
