# Generated by Django 4.2.11 on 2026-05-19 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costos_app', '0006_remove_proyecto_kwh_estimados_mes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturaFija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor_o_concepto', models.CharField(help_text='Ej: AWS Server, Claro Internet, Papelería S.A.', max_length=150)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mes_ano', models.CharField(help_text='Formato: AAAA-MM (Ej: 2026-05)', max_length=7)),
                ('clasificacion', models.CharField(choices=[('COSTO_OPERATIVO', 'Costo Operativo (AWS, GitHub, Telecomunicaciones, Licencias core)'), ('GASTO_ADMIN', 'Gasto Administrativo (Papelería, Arriendos, Software de soporte)')], default='COSTO_OPERATIVO', max_length=20)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Factura Fija',
                'verbose_name_plural': 'Facturas y Costos Fijos',
            },
        ),
    ]
