# Generated by Django 4.2.11 on 2026-05-20 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costos_app', '0007_facturafija'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivoFijo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_activo', models.CharField(help_text='Ej: MacBook Pro Desarrollador 1, Silla Ergonómica X', max_length=150)),
                ('tipo_activo', models.CharField(choices=[('COMPUTO', 'Equipo de Cómputo y Tecnología (Computadores, Servidores, Diademas)'), ('MUEBLES', 'Muebles y Enseres (Escritorios, Sillas, Cubículos)'), ('COMUNICACION', 'Equipos de Comunicación (Teléfonos corporativos)')], max_length=20)),
                ('valor_adquisicion', models.DecimalField(decimal_places=2, help_text='Valor histórico de compra o valor del derecho de uso', max_digits=12)),
                ('vida_util_meses', models.IntegerField(help_text='Vida útil estimada en meses (Ej: Cómputo 60 meses, Muebles 120 meses)')),
                ('fecha_adquisicion', models.DateField(help_text='Fecha en la que se compró o inició el contrato')),
                ('es_leasing', models.BooleanField(default=False, verbose_name='¿Es financiado mediante Leasing? (NIIF 16)')),
                ('tasa_interes_mensual', models.DecimalField(decimal_places=4, default=0.0, help_text='Tasa de interés mensual del leasing en decimal (Ej: 0.015 para 1.5%)', max_digits=5)),
                ('canon_mensual', models.DecimalField(decimal_places=2, default=0.0, help_text='El pago mensual fijo al banco', max_digits=12)),
            ],
            options={
                'verbose_name': 'Activo Fijo',
                'verbose_name_plural': 'Propiedad, Planta y Equipo',
            },
        ),
    ]
