# Generated by Django 4.2.11 on 2026-05-20 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costos_app', '0008_activofijo'),
    ]

    operations = [
        migrations.AddField(
            model_name='activofijo',
            name='empleado_asignado',
            field=models.ForeignKey(blank=True, help_text='Empleado que tiene en su poder el activo para operar', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activos', to='costos_app.empleado'),
        ),
    ]
