# Generated by Django 4.2.11 on 2026-05-20 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costos_app', '0009_activofijo_empleado_asignado'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresupuestoProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limite_costos', models.DecimalField(decimal_places=2, default=0.0, help_text='Presupuesto máximo para Costos Directos (Nómina MOD + Depreciación)', max_digits=12)),
                ('limite_gastos', models.DecimalField(decimal_places=2, default=0.0, help_text='Presupuesto máximo asignado para Gastos Operativos/Facturas indirectas', max_digits=12)),
                ('fecha_aprobacion', models.DateField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('proyecto', models.OneToOneField(help_text='Proyecto al que se le asigna este techo financiero', on_delete=django.db.models.deletion.CASCADE, related_name='presupuesto', to='costos_app.proyecto')),
            ],
            options={
                'verbose_name': 'Presupuestos de Proyectos',
            },
        ),
    ]
