# Generated by Django 4.2.11 on 2026-05-20 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costos_app', '0010_presupuestoproyecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacionproyecto',
            name='jefe_inmediato',
            field=models.ForeignKey(blank=True, help_text='Jefe directo del área o supervisor inmediato de la asignación', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinados_proyecto', to='costos_app.empleado'),
        ),
        migrations.AddField(
            model_name='asignacionproyecto',
            name='responsable_proyecto',
            field=models.ForeignKey(blank=True, help_text='El líder, director de TI o responsable principal de la ejecución de este proyecto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos_a_cargo', to='costos_app.empleado'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='email_corporativo',
            field=models.EmailField(blank=True, help_text='Correo oficial para notificaciones del ERP', max_length=254, null=True),
        ),
    ]
