# Generated by Django 4.2.11 on 2026-05-21 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costos_app', '0011_asignacionproyecto_jefe_inmediato_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturafija',
            name='proyecto',
            field=models.ForeignKey(blank=True, help_text='Seleccione el proyecto si este costo/gasto es imputable directamente a él', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas', to='costos_app.proyecto'),
        ),
    ]
