# Generated by Django 4.2.11 on 2026-05-21 22:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('costos_app', '0012_facturafija_proyecto'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idioma_preferido', models.CharField(choices=[('en-us', 'English (US)'), ('es', 'Español (América Latina)'), ('et', 'Eesti (Estonia)'), ('fi', 'Suomi (Finlandia)'), ('lt', 'Lietuvių (Lituania)')], default='en-us', help_text='Seleccione el idioma nativo para la interfaz del ERP', max_length=5)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuarios',
            },
        ),
    ]
