# Generated by Django 4.2.11 on 2026-05-23 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('costos_app', '0013_perfilusuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asignacionproyecto',
            options={'verbose_name': 'Asignación de Proyecto', 'verbose_name_plural': 'Asignaciones a Proyectos'},
        ),
        migrations.AlterModelOptions(
            name='empleado',
            options={'verbose_name': 'Empleado', 'verbose_name_plural': 'Empleados'},
        ),
        migrations.AlterModelOptions(
            name='pais',
            options={'verbose_name': 'País', 'verbose_name_plural': 'Países'},
        ),
        migrations.AlterModelOptions(
            name='presupuestoproyecto',
            options={'verbose_name': 'Presupuesto de Proyecto', 'verbose_name_plural': 'Presupuestos de Proyectos'},
        ),
        migrations.AlterModelOptions(
            name='proyecto',
            options={'verbose_name': 'Proyecto', 'verbose_name_plural': 'Proyectos'},
        ),
        migrations.AlterModelOptions(
            name='rol',
            options={'verbose_name': 'Rol / Cargo', 'verbose_name_plural': 'Roles / Cargos'},
        ),
        migrations.AddField(
            model_name='proyecto',
            name='kwh_estimados_mes',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Consumo proyectado de energía al mes en kWh', max_digits=10, verbose_name='kWh Estimados Mes'),
        ),
        migrations.AlterField(
            model_name='activofijo',
            name='canon_mensual',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='El pago mensual fijo al banco', max_digits=12, verbose_name='Canon Mensual'),
        ),
        migrations.AlterField(
            model_name='activofijo',
            name='empleado_asignado',
            field=models.ForeignKey(blank=True, help_text='Empleado que tiene en su poder el activo para operar', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activos', to='costos_app.empleado', verbose_name='Empleado Asignado'),
        ),
        migrations.AlterField(
            model_name='activofijo',
            name='fecha_adquisicion',
            field=models.DateField(help_text='Fecha en la que se compró o inició el contrato', verbose_name='Fecha de Adquisición'),
        ),
        migrations.AlterField(
            model_name='activofijo',
            name='nombre_activo',
            field=models.CharField(help_text='Ej: MacBook Pro, Silla Ergonómica', max_length=150, verbose_name='Nombre del Activo'),
        ),
        migrations.AlterField(
            model_name='activofijo',
            name='tasa_interes_mensual',
            field=models.DecimalField(decimal_places=4, default=0.0, help_text='Tasa de interés mensual del leasing', max_digits=5, verbose_name='Tasa Interés Mensual'),
        ),
        migrations.AlterField(
            model_name='activofijo',
            name='tipo_activo',
            field=models.CharField(choices=[('COMPUTO', 'Equipo de Cómputo y Tecnología (Computadores, Servidores)'), ('MUEBLES', 'Muebles y Enseres (Escritorios, Sillas)'), ('COMUNICACION', 'Equipos de Comunicación (Teléfonos corporativos)')], max_length=20, verbose_name='Tipo de Activo'),
        ),
        migrations.AlterField(
            model_name='activofijo',
            name='valor_adquisicion',
            field=models.DecimalField(decimal_places=2, help_text='Valor histórico de compra', max_digits=12, verbose_name='Valor de Adquisición'),
        ),
        migrations.AlterField(
            model_name='activofijo',
            name='vida_util_meses',
            field=models.IntegerField(help_text='Vida útil estimada en meses', verbose_name='Vida Útil (Meses)'),
        ),
        migrations.AlterField(
            model_name='asignacionproyecto',
            name='costo_imputado_al_proyecto',
            field=models.FloatField(default=0.0, verbose_name='Costo Imputado al Proyecto'),
        ),
        migrations.AlterField(
            model_name='asignacionproyecto',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='costos_app.empleado', verbose_name='Colaborador'),
        ),
        migrations.AlterField(
            model_name='asignacionproyecto',
            name='horas_dedicadas',
            field=models.FloatField(verbose_name='Horas Dedicadas en el Mes'),
        ),
        migrations.AlterField(
            model_name='asignacionproyecto',
            name='jefe_inmediato',
            field=models.ForeignKey(blank=True, help_text='Jefe directo del área o supervisor inmediato de la asignación', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinados_proyecto', to='costos_app.empleado', verbose_name='Jefe Inmediato'),
        ),
        migrations.AlterField(
            model_name='asignacionproyecto',
            name='mes_ano',
            field=models.CharField(max_length=7, verbose_name='Periodo Contable (Mes/Año)'),
        ),
        migrations.AlterField(
            model_name='asignacionproyecto',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='costos_app.proyecto', verbose_name='Unidad de Negocio / Proyecto'),
        ),
        migrations.AlterField(
            model_name='asignacionproyecto',
            name='responsable_proyecto',
            field=models.ForeignKey(blank=True, help_text='El líder, director de TI o responsable principal de la ejecución', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos_a_cargo', to='costos_app.empleado', verbose_name='Responsable del Proyecto'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='costo_seguridad_social_mes',
            field=models.FloatField(default=0.0, verbose_name='Costo Seguridad Social Mes'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='email_corporativo',
            field=models.EmailField(blank=True, help_text='Correo oficial para notificaciones del ERP', max_length=254, null=True, verbose_name='Correo Corporativo'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fecha_ingreso',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de Ingreso'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre Completo'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empleados', to='costos_app.pais', verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='provision_prestaciones_mes',
            field=models.FloatField(default=0.0, verbose_name='Provisión Prestaciones Mes'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='rol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleados', to='costos_app.rol', verbose_name='Rol / Cargo'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='salario_bruto_mensual',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salario Bruto Mensual'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='tipo_contrato',
            field=models.CharField(choices=[('INDEFINIDO', 'Término Indefinido'), ('FIJO', 'Término Fijo / Obra')], default='INDEFINIDO', max_length=10, verbose_name='Tipo de Contrato'),
        ),
        migrations.AlterField(
            model_name='facturafija',
            name='clasificacion',
            field=models.CharField(choices=[('COSTO_OPERATIVO', 'Costo Operativo (AWS, GitHub, Licencias core)'), ('GASTO_ADMIN', 'Gasto Administrativo (Papelería, Arriendos)')], default='COSTO_OPERATIVO', max_length=20, verbose_name='Clasificación'),
        ),
        migrations.AlterField(
            model_name='facturafija',
            name='fecha_registro',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='facturafija',
            name='mes_ano',
            field=models.CharField(help_text='Formato: AAAA-MM', max_length=7, verbose_name='Mes/Año'),
        ),
        migrations.AlterField(
            model_name='facturafija',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto'),
        ),
        migrations.AlterField(
            model_name='facturafija',
            name='proveedor_o_concepto',
            field=models.CharField(help_text='Ej: AWS Server, Claro Internet', max_length=150, verbose_name='Proveedor o Concepto'),
        ),
        migrations.AlterField(
            model_name='facturafija',
            name='proyecto',
            field=models.ForeignKey(blank=True, help_text='Seleccione el proyecto si este costo/gasto es imputable directamente a él', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas', to='costos_app.proyecto', verbose_name='Proyecto'),
        ),
        migrations.AlterField(
            model_name='pais',
            name='codigo_iso',
            field=models.CharField(max_length=3, unique=True, verbose_name='Código ISO (2 letras)'),
        ),
        migrations.AlterField(
            model_name='pais',
            name='nombre',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nombre del País'),
        ),
        migrations.AlterField(
            model_name='pais',
            name='salario_minimo',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salario Mínimo'),
        ),
        migrations.AlterField(
            model_name='pais',
            name='tasa_patronal_estandar',
            field=models.DecimalField(decimal_places=4, max_digits=5, verbose_name='Tasa Patronal Estándar (%)'),
        ),
        migrations.AlterField(
            model_name='pais',
            name='tasa_patronal_temporal',
            field=models.DecimalField(decimal_places=4, max_digits=5, verbose_name='Tasa Patronal Temporal (%)'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='idioma_preferido',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Español'), ('et', 'Eesti (Estonia)'), ('fi', 'Suomi (Finlandia)'), ('lt', 'Lietuvių (Lituania)'), ('da', 'Dansk (Danés)')], default='en', help_text='Seleccione el idioma nativo para la interfaz del ERP', max_length=5, verbose_name='Idioma Preferido'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='politicacontratacion',
            name='duracion_maxima_meses',
            field=models.IntegerField(blank=True, help_text='Duración máxima permitida por ley. Dejar vacío si no aplica.', null=True, verbose_name='Duración Máxima (Meses)'),
        ),
        migrations.AlterField(
            model_name='politicacontratacion',
            name='observacion_legal',
            field=models.TextField(blank=True, help_text='Notas o textos legales adicionales sobre las condiciones de despido o preaviso.', null=True, verbose_name='Observación Legal'),
        ),
        migrations.AlterField(
            model_name='politicacontratacion',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='politicas_contratacion', to='costos_app.pais', verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='politicacontratacion',
            name='periodo_prueba_maximo_meses',
            field=models.IntegerField(default=3, help_text='Meses máximos de prueba permitidos por la legislación local.', verbose_name='Periodo Prueba Máximo (Meses)'),
        ),
        migrations.AlterField(
            model_name='politicacontratacion',
            name='porcentaje_maximo_nomina',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Límite de empleados con este contrato.', max_digits=5, null=True, verbose_name='Porcentaje Máximo Nómina (%)'),
        ),
        migrations.AlterField(
            model_name='politicacontratacion',
            name='tipo_contrato',
            field=models.CharField(choices=[('INDEFINIDO', 'Término Indefinido'), ('FIJO', 'Término Fijo / Obra')], help_text='El tipo de contrato al que se le aplicará esta norma legal', max_length=10, verbose_name='Tipo de Contrato'),
        ),
        migrations.AlterField(
            model_name='presupuestoproyecto',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado en'),
        ),
        migrations.AlterField(
            model_name='presupuestoproyecto',
            name='fecha_aprobacion',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de Aprobación'),
        ),
        migrations.AlterField(
            model_name='presupuestoproyecto',
            name='limite_costos',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Límite de Costos Directos'),
        ),
        migrations.AlterField(
            model_name='presupuestoproyecto',
            name='limite_gastos',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Límite de Gastos Indirectos'),
        ),
        migrations.AlterField(
            model_name='presupuestoproyecto',
            name='proyecto',
            field=models.OneToOneField(help_text='Proyecto al que se le asigna este techo financiero', on_delete=django.db.models.deletion.CASCADE, related_name='presupuesto', to='costos_app.proyecto', verbose_name='Proyecto'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='nombre',
            field=models.CharField(max_length=150, verbose_name='Nombre del Proyecto'),
        ),
        migrations.AlterField(
            model_name='registroenergia',
            name='año',
            field=models.IntegerField(verbose_name='Año'),
        ),
        migrations.AlterField(
            model_name='registroenergia',
            name='costo_total_recibo',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Costo Total Recibo'),
        ),
        migrations.AlterField(
            model_name='registroenergia',
            name='mes',
            field=models.IntegerField(verbose_name='Mes'),
        ),
        migrations.AlterField(
            model_name='registroenergia',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos_energia', to='costos_app.pais', verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='registroenergia',
            name='total_kwh_consumidos_real',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total kWh Consumidos Real'),
        ),
        migrations.AlterField(
            model_name='rol',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='rol',
            name='nombre_cargo',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre del Cargo'),
        ),
        migrations.AlterField(
            model_name='rol',
            name='tipo_contable',
            field=models.CharField(choices=[('COSTO', 'Costo (Mano de Obra Directa / Operación)'), ('GASTO', 'Gasto (Administrativo / Ventas)')], default='COSTO', max_length=5, verbose_name='Tipo Contable'),
        ),
    ]
