"""
Django settings for costosproyectos project.

Generated by 'django-admin startproject' using Django 6.0.5.
"""
from django.utils.translation import gettext_lazy as _
from pathlib import Path
import os
import environ

# Inicializamos django-environ
env = environ.Env(
    DEBUG=(bool, False)
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# 🚀 LE DECIMOS A LA LIBRERÍA QUE LEA EL ARCHIVO .ENV
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

ALLOWED_HOSTS = []

# Application definition
INSTALLED_APPS = [
    "unfold",            
    "unfold.contrib.filters",  
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'costos_app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware', 
    
    # 🔥 ACTIVADO: El motor nativo de Django para gestionar los idiomas en el navegador
    'django.middleware.locale.LocaleMiddleware', 

    'django.middleware.common.CommonMiddleware', 
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware', 
]

ROOT_URLCONF = 'costosproyectos.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'costosproyectos.wsgi.application'

# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    { 'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator' },
    { 'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator' },
    { 'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator' },
    { 'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator' },
]

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

# Idioma por defecto (Cámbialo a 'es' si quieres ver tu Admin en español al inicio, u a 'da' para Danés)
LANGUAGE_CODE = 'en'

# ¡CRITICAL! Activa el motor de traducción local
USE_I18N = True
TIME_ZONE = 'UTC'
USE_TZ = True

# Formato corregido estándar para los idiomas disponibles
LANGUAGES = [
    ('en', _('English')), 
    ('es', _('Spanish')),
    ('fi', _('Finnish')),
    ('et', _('Estonian')),
    ('lt', _('Lithuanian')),
    ('lv', _('Latvian')),
    ('da', _('Danish')),
    ('de', _('German')),
    ('de-ch', _('Swiss German')),
    ('fr-ch', _('Swiss French')),
    ('it-ch', _('Swiss Italian')),
]

# 🚀 LE DECIMOS A DJANGO DÓNDE BUSCAR LOS ARCHIVOS .PO y .MO LOCALES
LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),
]

# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configuración de Autenticación de Django
LOGIN_URL = 'login'  
LOGIN_REDIRECT_URL = '/dashboard/' 

# Configuración de Email SMTP
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = env('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD')

# Configuración Tema Unfold Elegante
UNFOLD = {
    "SITE_TITLE": "ERP ABC Finanzas",
    "SITE_HEADER": "ABC Control de Costos",
    "SITE_SUBHEADER": "Panel de Control Contable y Presupuestal",
    "SHOW_HISTORY": True, 
    "SHOW_SIDEBAR_FILTER": True, 
}